name: quill_native_bridge
description: "An internal Flutter plugin for flutter_quill package to access platform-specific APIs"
version: 11.4.1
homepage: https://github.com/Sebastien-VZN/quill_native_bridge_robust
repository: https://github.com/Sebastien-VZN/quill_native_bridge_robust
issue_tracker: https://github.com/Sebastien-VZN/quill_native_bridge_robust/issues
publish_to: none
resolution: workspace

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  dart_quill_delta:
    git:
      url: https://github.com/Sebastien-VZN/dart_quill_delta_robust.git
  html: ^0.15.0
  markdown: ^7.1.0
  collection: ^1.17.0
  charcode: ^1.3.0
  flutter_quill_delta_from_html:
    git:
      url: https://github.com/Sebastien-VZN/flutter_quill_delta_from_html_robust.git
  quill_native_bridge_android:
    path: ../quill_native_bridge_android
  quill_native_bridge_platform_interface:
    path: ../quill_native_bridge_platform_interface
  quill_native_bridge_web:
    path: ../quill_native_bridge_web
  quill_native_bridge_windows:
    path: ../quill_native_bridge_windows
  quill_native_bridge_ios:
    path: ../quill_native_bridge_ios
  quill_native_bridge_macos:
    path: ../quill_native_bridge_macos
  quill_native_bridge_linux:
    path: ../quill_native_bridge_linux

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0
  mockito: ^5.4.5
  build_runner: ^2.4.13
  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    platforms:
      android:
        default_package: quill_native_bridge_android
      ios:
        default_package: quill_native_bridge_ios
      macos:
        default_package: quill_native_bridge_macos
      web:
        default_package: quill_native_bridge_web
      windows:
        default_package: quill_native_bridge_windows
      linux:
        default_package: quill_native_bridge_linux