name: quill_native_bridge_windows
description: "Windows implementation of the quill_native_bridge plugin."
version: 0.2.0
homepage: https://github.com/Sebastien-VZN/quill_native_bridge_robust
repository: https://github.com/Sebastien-VZN/quill_native_bridge_robust
publish_to: none
resolution: workspace

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  quill_native_bridge_platform_interface:
    path: ../quill_native_bridge_platform_interface
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  plugin:
    implements: quill_native_bridge
    platforms:
      windows:
        dartPluginClass: QuillNativeBridgeWindows
        fileName: quill_native_bridge_windows.dart